---
title: "p8105_hw5_xh2470"
output: github_document
---

```{r setup}
library(tidyverse)
library(readxl)

knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```

# Problem 1

Import and clean the data.

```{r}
homicide_df = 
  read_csv("./p1_data/homicide-data.csv", na = c("","Unknown")) %>% 
  mutate(
    city_state = str_c(city, state),
    resolution = case_when(
      disposition == "Closed without arrest" ~ "unsolved",
      disposition == "Open/No arrest" ~ "unsolved",
      disposition == "Closed by arrest" ~ "solved"
    )
  ) %>%
  relocate(city_state) %>%
  filter(city_state != "TulsaAL")
```

This data focused on homicides in 50 large U.S. cities.

Let's focus on Baltimore, MD.

```{r}
baltimore_df = 
  homicide_df %>% 
  filter(city_state == "BaltimoreMD")

baltimore_summary = 
  baltimore_df %>% 
  summarize(
    unsolved = sum(resolution == "unsolved"),
    n = n()
  )

baltimore_test = 
  prop.test(
  x = baltimore_summary %>% pull(unsolved),
  n = baltimore_summary %>% pull(n)
)

baltimore_test %>% 
  broom::tidy()

```

Let's try to iterate across cities!

```{r}
#First off, write a function.

prop_test_function = function(city_df){
  
  city_summary = 
    city_df %>%
    summarize(
      unsolved = sum(resolution == "unsolved"),
      n = n()
      )
  
  city_test = 
    prop.test(
      x = city_summary %>% pull(unsolved),
      n = city_summary %>% pull(n)
      )
  
  return(city_test)
  
}


prop_test_function(baltimore_df)

homicide_df %>% 
  filter(city_state == "AlbuquerqueNM") %>% 
  prop_test_function()


```


```{r}
# iterate across all cities

results_df = 
  homicide_df %>% 
  nest(data = uid:resolution) %>% 
  mutate(
    test_results = map(data,prop_test_function),
    tidy_results = map(test_results, broom::tidy)
  ) %>% 
  select(city_state, tidy_results) %>% 
  unnest(tidy_results) %>% 
  select(city_state, estimate, starts_with("conf"))

results_df

# another way of iteration
homicide_df %>% 
  group_by(city_state) %>% 
  summarize(
    unsolved = sum(resolution == "unsolved"),
    n = n()
  ) %>% 
  mutate(
    test_results = map2(unsolved, n, prop.test),
    tidy_results = map(test_results, broom::tidy)
  ) %>% 
  select(city_state, tidy_results) %>% 
  unnest(tidy_results) %>% 
  select(city_state, estimate, starts_with("conf"))

```


Make a plot showing estimates and confidence intervals.

```{r}
results_df %>% 
  mutate(city_state = fct_reorder(city_state, estimate)) %>% 
  ggplot(aes(x = city_state, y = estimate)) + 
  geom_point() +
  geom_errorbar(aes(ymin = conf.low, ymax = conf.high)) +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1))
```


# Problem 2

```{r}
# Create a dataframe containing all file names
df = tibble( file = list.files(path = "./hw5_data", full.names = TRUE))


# Iterate over file names and read in data for each subject 
read_data = function(x) {
  data = read_csv(x)
  }

df = 
  df %>% 
  mutate(data = purrr::map(pull(df,file), read_data)) 

# Tidy the result
df = 
  df %>% 
  unnest(data) %>% 
  separate(file, into = c("arm", "subject_ID"), sep = 3) %>% 
  mutate(arm = recode(arm, `con` = "control", `exp` = "experiment" ),
         subject_ID = substring(subject_ID,2,3)) 
```

# Problem 3

```{r}
# loads the iris dataset 
set.seed(10)

iris_with_missing = 
  iris %>% 
  map_df(~replace(.x, sample(1:150, 20), NA)) %>%
  mutate(Species = as.character(Species))

# fill in missing values
fill_in_missing = function(vector) {
  
  if (is.numeric(vector)) 
    {
    vector = ifelse(is.na(vector), mean(vector, na.rm = TRUE), vector)
    } 
  
  if (is.character(vector)) {
    vector = ifelse(is.na(vector), "virginica", vector)
  } 
  
  }
  
x = purrr::map(iris_with_missing, fill_in_missing) 
```

